imports:
    - { resource: tables.yml }
parameters:
    ultimatepoints.version_data:
        author: dmzx & posey
        title: Ultimate Points
        version: ultimate_points_version
        file:
            - www.dmzx-web.net
            - /versions
            - ultimatepoints_version.json
services:
    dmzx.ultimatepoints.version.check:
        class: dmzx\ultimatepoints\includes\version_check
        scope: prototype
        arguments:
            - '%ultimatepoints.version_data%'
            - '@config'
            - '@version_helper'
            - '@template'
            - '@user'
    dmzx.ultimatepoints.listener:
        class: dmzx\ultimatepoints\event\listener
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@user'
            - '@template'
            - '@dbal.conn'
            - '@config'
            - '@auth'
            - '@controller.helper'
            - '@cache'
            - '@request'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.ultimatepoints.table.points.bank%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'
            - '@?files.factory'
        tags:
            - { name: event.listener }

    dmzx.ultimatepoints.controller:
        class: dmzx\ultimatepoints\controller\main
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@dmzx.ultimatepoints.core.points.main'
            - '@dmzx.ultimatepoints.core.points.info'
            - '@dmzx.ultimatepoints.core.points.transfer.user'
            - '@dmzx.ultimatepoints.core.points.bank'
            - '@dmzx.ultimatepoints.core.points.logs'
            - '@dmzx.ultimatepoints.core.points.bank.edit'
            - '@dmzx.ultimatepoints.core.points.lottery'
            - '@dmzx.ultimatepoints.core.points.points.edit'
            - '@dmzx.ultimatepoints.core.points.robbery'
            - '@dmzx.ultimatepoints.core.points.robbery.user'
            - '@dmzx.ultimatepoints.core.points.transfer'
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.list.controller:
        class: dmzx\ultimatepoints\controller\userlist
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@pagination'
            - '@controller.helper'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.admin.controller:
        class: dmzx\ultimatepoints\controller\admin_controller
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@template'
            - '@user'
            - '@auth'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@log'
            - '@cache'
            - '@service_container'
            - '%core.root_path%'
            - '%core.adm_relative_path%'
            - '%core.php_ext%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.notification.type.points:
        class: dmzx\ultimatepoints\notification\points
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }

    dmzx.ultimatepoints.core.functions.points:
        class: dmzx\ultimatepoints\core\functions_points
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@controller.helper'
            - '@notification_manager'
            - '@log'
            - '@cache'
            - '@request'
            - '@config'
            - '@pagination'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.bank%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.lottery.history%'
            - '%dmzx.ultimatepoints.table.points.lottery.tickets%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.core.points.main:
        class: dmzx\ultimatepoints\core\points_main
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.bank%'
            - '%dmzx.ultimatepoints.table.points.values%'
            - '%dmzx.ultimatepoints.table.points.log%'
            - '%dmzx.ultimatepoints.table.points.lottery.tickets%'
            - '%dmzx.ultimatepoints.table.points.lottery.history%'

    dmzx.ultimatepoints.core.points.info:
        class: dmzx\ultimatepoints\core\points_info
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@dbal.conn'
            - '@template'
            - '@user'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.core.points.transfer.user:
        class: dmzx\ultimatepoints\core\points_transfer_user
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.log%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.core.points.bank:
        class: dmzx\ultimatepoints\core\points_bank
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@log'
            - '@notification_manager'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.bank%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.core.points.logs:
        class: dmzx\ultimatepoints\core\points_logs
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@pagination'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.log%'
            - '%dmzx.ultimatepoints.table.points.values%'

    dmzx.ultimatepoints.core.points.bank.edit:
        class: dmzx\ultimatepoints\core\points_bank_edit
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@log'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.bank%'

    dmzx.ultimatepoints.core.points.lottery:
        class: dmzx\ultimatepoints\core\points_lottery
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@pagination'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'
            - '%dmzx.ultimatepoints.table.points.lottery.history%'
            - '%dmzx.ultimatepoints.table.points.lottery.tickets%'

    dmzx.ultimatepoints.core.points.points.edit:
        class: dmzx\ultimatepoints\core\points_points_edit
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@log'
            - '@request'
            - '%core.php_ext%'
            - '%core.root_path%'

    dmzx.ultimatepoints.core.points.robbery:
        class: dmzx\ultimatepoints\core\points_robbery
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@notification_manager'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'
            - '%dmzx.ultimatepoints.table.points.log%'
    dmzx.ultimatepoints.core.points.robbery.user:
        class: dmzx\ultimatepoints\core\points_robbery_user
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '@notification_manager'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'
            - '%dmzx.ultimatepoints.table.points.log%'
    dmzx.ultimatepoints.core.points.transfer:
        class: dmzx\ultimatepoints\core\points_transfer
        arguments:
            - '@dmzx.ultimatepoints.core.functions.points'
            - '@auth'
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@request'
            - '@config'
            - '@controller.helper'
            - '%core.php_ext%'
            - '%core.root_path%'
            - '%dmzx.ultimatepoints.table.points.log%'
            - '%dmzx.ultimatepoints.table.points.config%'
            - '%dmzx.ultimatepoints.table.points.values%'